[pytest]
addopts = --strict-markers --tb=short --maxfail=1 --cov=./ --cov-report=term-missing --cov-report=xml --cov-fail-under=95
python_files = tests/test_*.py
markers =
    asyncio: mark async tests